import { useState, type CSSProperties } from 'react';

/**
 * Image optimization.
 *
 * Every raster image on the site goes through this component so the same
 * guarantees hold everywhere: an explicit aspect ratio (no layout shift),
 * lazy loading below the fold, async decoding, a responsive srcset, and a
 * blurred placeholder that cross-fades to the real file.
 */

export interface OptimizedImageProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Loads eagerly and gets fetchpriority=high — use for the LCP image only. */
  priority?: boolean;
  sizes?: string;
  className?: string;
  style?: CSSProperties;
}

/** Widths generated by the asset pipeline for every source image. */
const WIDTHS = [480, 768, 1024, 1440, 1920];

const buildSrcSet = (src: string): string | undefined => {
  // Only files served by our own pipeline get variants; anything else
  // (an absolute URL, an SVG) is used as-is.
  if (/^https?:/.test(src) || src.endsWith('.svg')) return undefined;
  const dot = src.lastIndexOf('.');
  if (dot < 0) return undefined;
  const base = src.slice(0, dot);
  const ext = src.slice(dot);
  return WIDTHS.map((width) => `${base}-${width}w${ext} ${width}w`).join(', ');
};

export const OptimizedImage = ({
  src,
  alt,
  width,
  height,
  priority = false,
  sizes = '(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw',
  className,
  style,
}: OptimizedImageProps) => {
  const [loaded, setLoaded] = useState(false);
  const srcSet = buildSrcSet(src);

  return (
    <img
      src={src}
      srcSet={srcSet}
      sizes={srcSet ? sizes : undefined}
      alt={alt}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      decoding={priority ? 'sync' : 'async'}
      fetchPriority={priority ? 'high' : 'auto'}
      onLoad={() => setLoaded(true)}
      className={className}
      style={{
        aspectRatio: `${width} / ${height}`,
        objectFit: 'cover',
        backgroundColor: 'var(--oph-surface-3)',
        opacity: loaded || priority ? 1 : 0,
        transition: 'opacity 520ms var(--oph-ease-out)',
        ...style,
      }}
    />
  );
};

/**
 * A doctor's portrait.
 *
 * When the clinic has supplied a photograph of that doctor, it is used. Until
 * then the card shows a photograph of the centre itself under a brand wash,
 * with the doctor's initials over it — a real picture, of a real place, that
 * makes no claim about whose face it is.
 *
 * Deliberately never a stock or generated face. These are named clinicians on a
 * medical site: a face that is not theirs misleads the patient about who they
 * are booking with, and misattributes a medical role to whoever was actually
 * photographed. Drop the real portraits into /public/media/doctors, set `photo`
 * on the record in data/doctors.json, and every card, the detail page and the
 * management page pick them up with no other change.
 */


export const DoctorPortrait = ({
  photo,
  seed,
  label,
  className,
}: {
  photo?: string;
  seed: string;
  label: string;
  className?: string;
}) => {
  const initials = label
    .split(' ')
    .slice(0, 2)
    .map((part) => part[0])
    .join('');

  if (photo) {
    return (
      <img
        className={className}
        src={photo}
        alt={label}
        width={600}
        height={800}
        loading="lazy"
        decoding="async"
        style={{ width: '100%', height: '100%', objectFit: 'cover' }}
      />
    );
  }

  // No portrait yet: an editorial monogram card (Figma error 4 — initials were
  // pasted over clinic photos). Forest paper, gold serif monogram, iris rings.
  const hash = [...seed].reduce((acc, char) => (acc * 33 + char.charCodeAt(0)) >>> 0, 5381);
  return (
    <div className={`oph-portrait ${className ?? ''}`} role="img" aria-label={label} data-tone={hash % 3}>
      <span className="oph-portrait__rings" aria-hidden="true" />
      <span className="oph-portrait__initials" aria-hidden="true">
        {initials}
      </span>
    </div>
  );
};
