import * as home from '../../../frontend/src/content/pages/home';
import * as people_founder from '../../../frontend/src/content/pages/people-founder';
import * as people from '../../../frontend/src/content/pages/people';
import * as patients from '../../../frontend/src/content/pages/patients';
import * as patients_international from '../../../frontend/src/content/pages/patients-international';
import * as patients_second_opinion from '../../../frontend/src/content/pages/patients-second-opinion';
import * as patients_consultation from '../../../frontend/src/content/pages/patients-consultation';
import * as people_network from '../../../frontend/src/content/pages/people-network';
import * as science from '../../../frontend/src/content/pages/science';
import * as science_publications from '../../../frontend/src/content/pages/science-publications';
import * as academy from '../../../frontend/src/content/pages/academy';
import * as media from '../../../frontend/src/content/pages/media';
import * as knowledge from '../../../frontend/src/content/pages/knowledge';
import * as knowledge_articles_index from '../../../frontend/src/content/pages/knowledge-articles-index';
import * as platform from '../../../frontend/src/content/pages/platform';
import * as overlays from '../../../frontend/src/content/pages/overlays';
import * as services from '../../../frontend/src/content/pages/services';
import * as services_content from '../../../frontend/src/content/pages/services-content';
const sb: Record<string, unknown> = {};
import sb_complex_diagnostics from '../../../frontend/src/content/pages/services-bodies/complex-diagnostics.ts'; sb['complex-diagnostics']=sb_complex_diagnostics;
import sb_consultation_ophthalmologist from '../../../frontend/src/content/pages/services-bodies/consultation-ophthalmologist.ts'; sb['consultation-ophthalmologist']=sb_consultation_ophthalmologist;
import sb_contact_lens_fitting from '../../../frontend/src/content/pages/services-bodies/contact-lens-fitting.ts'; sb['contact-lens-fitting']=sb_contact_lens_fitting;
import sb_corneal_topography from '../../../frontend/src/content/pages/services-bodies/corneal-topography.ts'; sb['corneal-topography']=sb_corneal_topography;
import sb_dry_eye from '../../../frontend/src/content/pages/services-bodies/dry-eye.ts'; sb['dry-eye']=sb_dry_eye;
import sb_femto_lasik from '../../../frontend/src/content/pages/services-bodies/femto-lasik.ts'; sb['femto-lasik']=sb_femto_lasik;
import sb_glasses_fitting from '../../../frontend/src/content/pages/services-bodies/glasses-fitting.ts'; sb['glasses-fitting']=sb_glasses_fitting;
import sb_glaucoma_treatment from '../../../frontend/src/content/pages/services-bodies/glaucoma-treatment.ts'; sb['glaucoma-treatment']=sb_glaucoma_treatment;
import sb_hardware_therapy from '../../../frontend/src/content/pages/services-bodies/hardware-therapy.ts'; sb['hardware-therapy']=sb_hardware_therapy;
import sb_intravitreal_injection from '../../../frontend/src/content/pages/services-bodies/intravitreal-injection.ts'; sb['intravitreal-injection']=sb_intravitreal_injection;
import sb_myopia_control from '../../../frontend/src/content/pages/services-bodies/myopia-control.ts'; sb['myopia-control']=sb_myopia_control;
import sb_oct from '../../../frontend/src/content/pages/services-bodies/oct.ts'; sb['oct']=sb_oct;
import sb_pediatric_consultation from '../../../frontend/src/content/pages/services-bodies/pediatric-consultation.ts'; sb['pediatric-consultation']=sb_pediatric_consultation;
import sb_perimetry from '../../../frontend/src/content/pages/services-bodies/perimetry.ts'; sb['perimetry']=sb_perimetry;
import sb_phacoemulsification_multifocal from '../../../frontend/src/content/pages/services-bodies/phacoemulsification-multifocal.ts'; sb['phacoemulsification-multifocal']=sb_phacoemulsification_multifocal;
import sb_phacoemulsification from '../../../frontend/src/content/pages/services-bodies/phacoemulsification.ts'; sb['phacoemulsification']=sb_phacoemulsification;
import sb_prk from '../../../frontend/src/content/pages/services-bodies/prk.ts'; sb['prk']=sb_prk;
import sb_retina_treatment from '../../../frontend/src/content/pages/services-bodies/retina-treatment.ts'; sb['retina-treatment']=sb_retina_treatment;
import sb_smile from '../../../frontend/src/content/pages/services-bodies/smile.ts'; sb['smile']=sb_smile;
import sb_yag_capsulotomy from '../../../frontend/src/content/pages/services-bodies/yag-capsulotomy.ts'; sb['yag-capsulotomy']=sb_yag_capsulotomy;
const kb: Record<string, unknown> = {};
import kb_age_related_macular_degeneration from '../../../frontend/src/content/pages/knowledge-bodies/age-related-macular-degeneration.ts'; kb['age-related-macular-degeneration']=kb_age_related_macular_degeneration;
import kb_ai_in_retinal_imaging from '../../../frontend/src/content/pages/knowledge-bodies/ai-in-retinal-imaging.ts'; kb['ai-in-retinal-imaging']=kb_ai_in_retinal_imaging;
import kb_child_myopia_progression from '../../../frontend/src/content/pages/knowledge-bodies/child-myopia-progression.ts'; kb['child-myopia-progression']=kb_child_myopia_progression;
import kb_contact_lens_care from '../../../frontend/src/content/pages/knowledge-bodies/contact-lens-care.ts'; kb['contact-lens-care']=kb_contact_lens_care;
import kb_diabetic_retinopathy_screening from '../../../frontend/src/content/pages/knowledge-bodies/diabetic-retinopathy-screening.ts'; kb['diabetic-retinopathy-screening']=kb_diabetic_retinopathy_screening;
import kb_eye_check_after_40 from '../../../frontend/src/content/pages/knowledge-bodies/eye-check-after-40.ts'; kb['eye-check-after-40']=kb_eye_check_after_40;
import kb_glaucoma_early_signs from '../../../frontend/src/content/pages/knowledge-bodies/glaucoma-early-signs.ts'; kb['glaucoma-early-signs']=kb_glaucoma_early_signs;
import kb_glaucoma_treatment_options from '../../../frontend/src/content/pages/knowledge-bodies/glaucoma-treatment-options.ts'; kb['glaucoma-treatment-options']=kb_glaucoma_treatment_options;
import kb_keratoconus_explained from '../../../frontend/src/content/pages/knowledge-bodies/keratoconus-explained.ts'; kb['keratoconus-explained']=kb_keratoconus_explained;
import kb_laser_correction_preparation from '../../../frontend/src/content/pages/knowledge-bodies/laser-correction-preparation.ts'; kb['laser-correction-preparation']=kb_laser_correction_preparation;
import kb_lazy_eye_and_squint_in_children from '../../../frontend/src/content/pages/knowledge-bodies/lazy-eye-and-squint-in-children.ts'; kb['lazy-eye-and-squint-in-children']=kb_lazy_eye_and_squint_in_children;
import kb_presbyopia_after_40 from '../../../frontend/src/content/pages/knowledge-bodies/presbyopia-after-40.ts'; kb['presbyopia-after-40']=kb_presbyopia_after_40;
import kb_retina_window_to_the_brain from '../../../frontend/src/content/pages/knowledge-bodies/retina-window-to-the-brain.ts'; kb['retina-window-to-the-brain']=kb_retina_window_to_the_brain;
import kb_retinal_detachment_warning_signs from '../../../frontend/src/content/pages/knowledge-bodies/retinal-detachment-warning-signs.ts'; kb['retinal-detachment-warning-signs']=kb_retinal_detachment_warning_signs;
import kb_screen_dry_eye from '../../../frontend/src/content/pages/knowledge-bodies/screen-dry-eye.ts'; kb['screen-dry-eye']=kb_screen_dry_eye;
import kb_structured_light_entoptic_tests from '../../../frontend/src/content/pages/knowledge-bodies/structured-light-entoptic-tests.ts'; kb['structured-light-entoptic-tests']=kb_structured_light_entoptic_tests;
import kb_when_to_operate_cataract from '../../../frontend/src/content/pages/knowledge-bodies/when-to-operate-cataract.ts'; kb['when-to-operate-cataract']=kb_when_to_operate_cataract;
import { writeFileSync } from 'node:fs';
const ru = (v: any): any => {
  if (Array.isArray(v)) return v.map(ru);
  if (typeof v === 'function') return undefined;
  if (v && typeof v === 'object') {
    if ('ru' in v && ('en' in v || 'kk' in v)) return ru(v.ru);
    const o: any = {};
    for (const k of Object.keys(v)) { const r = ru(v[k]); if (r !== undefined) o[k] = r; }
    return o;
  }
  return v;
};
const all = { home, people_founder, people, patients, patients_international, patients_second_opinion, patients_consultation, people_network, science, science_publications, academy, media, knowledge, knowledge_articles_index, platform, overlays, services, services_content, serviceBodies: sb, knowledgeBodies: kb };
writeFileSync(process.argv[2], JSON.stringify(ru(all), null, 1));
