// Rasterises Natural Earth 110m land (world-atlas) into a compact RLE bitmap.
import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';
import { geoContains } from 'd3-geo';
const topo = JSON.parse(readFileSync(new URL('../node_modules/world-atlas/land-110m.json', import.meta.url)));
const land = feature(topo, topo.objects.land);
const W = 720, H = 360; // 0.5 degree
const rows = [];
for (let y = 0; y < H; y++) {
  const lat = 90 - (y + 0.5) * (180 / H);
  const runs = []; let cur = 0, n = 0;
  for (let x = 0; x < W; x++) {
    const lng = -180 + (x + 0.5) * (360 / W);
    const v = geoContains(land, [lng, lat]) ? 1 : 0;
    if (v === cur) n++; else { runs.push(n); cur = v; n = 1; }
  }
  runs.push(n);
  rows.push(runs.join(','));
}
const out = `// generated by scripts/gen-land.mjs — Natural Earth 110m land, 0.5° RLE rows (alternating sea,land)\nexport const LAND_W = ${W};\nexport const LAND_H = ${H};\nexport const LAND_RLE = ${JSON.stringify(rows.join(';'))};\n`;
writeFileSync(new URL('../src/world/landmask.ts', import.meta.url), out);
console.log('bytes', out.length);
